knp_snappy:
    pdf:
        enabled:    true
        binary:     '%env(WKHTMLTOPDF_PATH)%'
        options:    [
            enable-local-file-access
        ]
    image:
        enabled:    true #see: https://github.com/symfony/symfony/issues/30059 (Remove unused env vars exception)
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
